// data/demos.ts
//
// AUTO-GENERATED by scripts/build-demo-data.mjs — do not hand-edit.
// Source: ..\campaign_outputs
// Regenerate with: npm run build:demo-data

export type MoodboardImage = {
  imagePath: string;
  photographer?: string;
  photographerProfile?: string;
  unsplashLink?: string;
};

export type DemoCampaign = {
  id: string;
  tileLabel: string;
  tileImage: string;
  prompt: string;
  copy: {
    headline: string;
    body_copy: string;
    target_audience: string;
    core_message: string;
    visual_concept: string;
  };
  pitch: {
    call_to_action: string;
    design_rationale: string;
  };
  imagePath: string;
  audioPath: string;
  moodboard: MoodboardImage[];
};

export const demoCampaigns: DemoCampaign[] = [
  {
    "id": "demo-1",
    "tileLabel": "Sneakers for those who build their own path.",
    "tileImage": "/demos/campaign-1/moodboard/unsplash_1.jpg",
    "prompt": "Launch a bold sneaker line targeting Gen Z, built around self-expression.",
    "copy": {
      "headline": "Defy the Mold. Define Your Flow.",
      "body_copy": "Your style isn't a rulebook, and neither are your kicks. Drop into our bold new sneaker line engineered for the unapologetic. Mix colors, break limits, and walk your talk.",
      "target_audience": "Gen Z trendsetters and creatives aged 16-25 who value individuality and bold fashion statements.",
      "core_message": "Express your true self without boundaries through a sneaker line designed to stand out.",
      "visual_concept": "A pair of vibrant, multi-colored chunky sneakers is placed diagonally as the central, dominant subject on a raw concrete pedestal. The background features a dynamic urban skatepark under soft, golden-hour sunset lighting with a shallow depth of field. Neon graffiti art is subtly blurred in the background. The composition is asymmetrical and modern, captured from a low angle to emphasize the sneaker's bold silhouette and rebellious aesthetic."
    },
    "pitch": {
      "call_to_action": "Drop into our bold new sneaker line and define your flow.",
      "design_rationale": "The asymmetrical composition, low-angle shot, and raw concrete pedestal emphasize the sneaker's rebellious silhouette and bold aesthetic, while the urban skatepark and golden-hour neon graffiti create an energetic, modern atmosphere."
    },
    "imagePath": "/demos/campaign-1/campaign_image.png",
    "audioPath": "/demos/campaign-1/audio.mp3",
    "moodboard": [
      {
        "imagePath": "/demos/campaign-1/moodboard/unsplash_1.jpg",
        "photographer": "wtrsnvc _",
        "photographerProfile": "https://unsplash.com/@wtrsnvc",
        "unsplashLink": "https://unsplash.com/photos/a-pair-of-sneakers-with-a-shoelace-on-top-of-them-y1XsLc4Y8IE"
      },
      {
        "imagePath": "/demos/campaign-1/moodboard/unsplash_2.jpg",
        "photographer": "wtrsnvc _",
        "photographerProfile": "https://unsplash.com/@wtrsnvc",
        "unsplashLink": "https://unsplash.com/photos/a-pair-of-sneakers-with-colorful-shoeslaces-on-them-UKAjZYTeKL0"
      },
      {
        "imagePath": "/demos/campaign-1/moodboard/unsplash_3.jpg",
        "photographer": "wtrsnvc _",
        "photographerProfile": "https://unsplash.com/@wtrsnvc",
        "unsplashLink": "https://unsplash.com/photos/a-pair-of-sneakers-with-a-white-background-K1enI0KZjMw"
      },
      {
        "imagePath": "/demos/campaign-1/moodboard/unsplash_4.jpg",
        "photographer": "Magnus Andersson",
        "photographerProfile": "https://unsplash.com/@majolixious",
        "unsplashLink": "https://unsplash.com/photos/person-in-black-white-and-orange-nike-shoes-dZJorqZxpYA"
      }
    ]
  },
  {
    "id": "demo-2",
    "tileLabel": "Sustainable Skincare",
    "tileImage": "/demos/campaign-2/moodboard/unsplash_1.jpg",
    "prompt": "Launch a sustainable skincare brand targeting environmentally conscious Gen Z consumers.",
    "copy": {
      "headline": "Pure Skin, Plant the Planet",
      "body_copy": "Meet EarthGlow: the 100% zero-waste skincare routine that loves your skin and the ecosystem. Formulated with ethically sourced botanicals, packaged in infinitely recyclable glass, and a tree planted for every single order. Glow consciously.",
      "target_audience": "Environmentally conscious Gen Z consumers aged 18-26 who value clean beauty, zero-waste lifestyles, and transparent brand ethics.",
      "core_message": "Skincare that heals your skin without harming the planet.",
      "visual_concept": "A hero shot of the EarthGlow moisturizer in a frosted green glass jar with a wooden lid, resting on a flat, smooth river stone. Fresh botanical leaves like aloe and eucalyptus are artfully arranged in the soft-focus background. Natural morning sunlight streams in from the side, casting gentle shadows and highlighting the clean, minimalist aesthetic. The composition is a top-down angled close-up emphasizing eco-luxury and natural purity."
    },
    "pitch": {
      "call_to_action": "Glow consciously and order your zero-waste skincare routine today.",
      "design_rationale": "The visual concept uses minimalist eco-luxury aesthetics, featuring natural morning sunlight, a frosted green glass jar, a wooden lid, and fresh botanicals on a river stone to visually reinforce themes of natural purity, sustainability, and premium quality."
    },
    "imagePath": "/demos/campaign-2/campaign_image.png",
    "audioPath": "/demos/campaign-2/audio.mp3",
    "moodboard": [
      {
        "imagePath": "/demos/campaign-2/moodboard/unsplash_1.jpg",
        "photographer": "Poko Skincare",
        "photographerProfile": "https://unsplash.com/@pokoskincare",
        "unsplashLink": "https://unsplash.com/photos/assorted-plastic-bottles-on-brown-woven-basket-hZ7wSMMWGMA"
      },
      {
        "imagePath": "/demos/campaign-2/moodboard/unsplash_2.jpg",
        "photographer": "Elsa Olofsson",
        "photographerProfile": "https://unsplash.com/@elsaolofsson",
        "unsplashLink": "https://unsplash.com/photos/black-and-white-labeled-bottle-Pm0K9Y3EPUc"
      },
      {
        "imagePath": "/demos/campaign-2/moodboard/unsplash_3.jpg",
        "photographer": "Poko Skincare",
        "photographerProfile": "https://unsplash.com/@pokoskincare",
        "unsplashLink": "https://unsplash.com/photos/white-and-clear-glass-container-on-brown-wooden-table-AxKIWMgUJOI"
      },
      {
        "imagePath": "/demos/campaign-2/moodboard/unsplash_4.jpg",
        "photographer": "Lume Wellness",
        "photographerProfile": "https://unsplash.com/@lume_wellness",
        "unsplashLink": "https://unsplash.com/photos/white-and-black-labeled-soft-tube-_HXI367NQrs"
      }
    ]
  },
  {
    "id": "demo-3",
    "tileLabel": "Productivity Apps",
    "tileImage": "/demos/campaign-3/moodboard/unsplash_1.jpg",
    "prompt": "Launch a modern productivity app targeting ambitious young professionals who want to focus and get more done.",
    "copy": {
      "headline": "Master Your Focus, Amplify Your Day",
      "body_copy": "Cut through the noise and achieve your biggest goals with our sleek, intuitive productivity app. Designed for ambitious professionals who demand results.",
      "target_audience": "Ambitious young professionals and entrepreneurs aged 24-35 seeking to optimize their workflow and eliminate distractions.",
      "core_message": "Streamline your workday and achieve peak performance effortlessly.",
      "visual_concept": "A sleek smartphone displaying the modern productivity app interface rests at a slight angle on a minimalist light wood desk. Beside the phone is a steaming ceramic mug of black coffee and a clean, bound leather notebook with a sleek pen. The background is a brightly lit, airy home office with soft-focus green plants near a large window. The lighting is bright and natural morning sunlight, casting soft shadows. The composition is clean, top-down angled with a shallow depth of field, emphasizing the crisp design of the app."
    },
    "pitch": {
      "call_to_action": "Master Your Focus, Amplify Your Day",
      "design_rationale": "A clean, top-down angled composition with bright natural morning sunlight, a minimalist light wood desk, a steaming mug of coffee, and soft-focus green plants creates an airy, inspiring, and distraction-free environment that mirrors the crisp and modern efficiency of the productivity app."
    },
    "imagePath": "/demos/campaign-3/campaign_image.png",
    "audioPath": "/demos/campaign-3/audio.mp3",
    "moodboard": [
      {
        "imagePath": "/demos/campaign-3/moodboard/unsplash_1.jpg",
        "photographer": "Balázs Kétyi",
        "photographerProfile": "https://unsplash.com/@balazsketyi",
        "unsplashLink": "https://unsplash.com/photos/black-android-smartphone-sScmok4Iq1o"
      },
      {
        "imagePath": "/demos/campaign-3/moodboard/unsplash_2.jpg",
        "photographer": "Tran Mau Tri Tam ✪",
        "photographerProfile": "https://unsplash.com/@tranmautritam",
        "unsplashLink": "https://unsplash.com/photos/person-holding-black-android-smartphone-QwAL909kTiY"
      },
      {
        "imagePath": "/demos/campaign-3/moodboard/unsplash_3.jpg",
        "photographer": "Brett Jordan",
        "photographerProfile": "https://unsplash.com/@brett_jordan",
        "unsplashLink": "https://unsplash.com/photos/black-and-gray-computer-keyboard-0rXUP7Tg7nQ"
      },
      {
        "imagePath": "/demos/campaign-3/moodboard/unsplash_4.jpg",
        "photographer": "Yohan Marion",
        "photographerProfile": "https://unsplash.com/@yohanmarion",
        "unsplashLink": "https://unsplash.com/photos/a-person-holding-up-a-smart-phone-in-their-hand-cTanNCqGYc4"
      }
    ]
  },
  {
    "id": "demo-4",
    "tileLabel": "Healthy Snack Finds",
    "tileImage": "/demos/campaign-4/moodboard/unsplash_1.jpg",
    "prompt": "Launch a healthy convenient snack brand targeting active college students who want nutritious food on the go.",
    "copy": {
      "headline": "Fuel Your All-Nighter Without the Crash",
      "body_copy": "Ditch the vending machine guilt. Grab our plant-based, protein-packed energy bites made for life between lectures, workouts, and study sessions.",
      "target_audience": "Active college students seeking quick, nutritious on-the-go fuel",
      "core_message": "Healthy snacking that keeps up with your busy student life.",
      "visual_concept": "A vibrant, product-first shot featuring a pouch of organic energy bites propped up on a clean wooden student desk next to a textbook and a shiny red apple. One bite is broken open in the foreground to reveal a rich, nutrient-dense texture with visible chia seeds and nuts. The background is a softly blurred college campus courtyard during golden hour. Bright, natural lighting highlights the matte texture of the packaging. Shot from a dynamic 45-degree angle with a shallow depth of field, creating an energetic and modern lifestyle advertising aesthetic."
    },
    "pitch": {
      "call_to_action": "Grab our plant-based, protein-packed energy bites today.",
      "design_rationale": "A vibrant, product-first shot set on a student desk with natural golden hour lighting creates an energetic and modern lifestyle aesthetic that resonates with students."
    },
    "imagePath": "/demos/campaign-4/campaign_image.png",
    "audioPath": "/demos/campaign-4/audio.mp3",
    "moodboard": [
      {
        "imagePath": "/demos/campaign-4/moodboard/unsplash_1.jpg",
        "photographer": "Abbie Whiddett",
        "photographerProfile": "https://unsplash.com/@abbiew",
        "unsplashLink": "https://unsplash.com/photos/brown-and-white-chocolate-cupcakes-e34KSdVAs1U"
      },
      {
        "imagePath": "/demos/campaign-4/moodboard/unsplash_2.jpg",
        "photographer": "Snappr",
        "photographerProfile": "https://unsplash.com/@snappr",
        "unsplashLink": "https://unsplash.com/photos/a-white-plate-topped-with-different-types-of-chocolates-kxo8aqgJ2sA"
      },
      {
        "imagePath": "/demos/campaign-4/moodboard/unsplash_3.jpg",
        "photographer": "Rachel Kelli",
        "photographerProfile": "https://unsplash.com/@rachelkelli",
        "unsplashLink": "https://unsplash.com/photos/a-wooden-plate-topped-with-slices-of-bread-covered-in-cheese-and-avocado-rLOVAm3DR3g"
      },
      {
        "imagePath": "/demos/campaign-4/moodboard/unsplash_4.jpg",
        "photographer": "Theo Lonic",
        "photographerProfile": "https://unsplash.com/@thorai9akira",
        "unsplashLink": "https://unsplash.com/photos/five-golden-nuggets-on-a-black-plate-nVYzmJTeOQI"
      }
    ]
  }
];
